2022-02-17 18:58:34,413 INFO    MainThread:85754 [internal.py:wandb_internal():89] W&B internal server running at pid: 85754, started at: 2022-02-17 18:58:34.413005
2022-02-17 18:58:34,482 DEBUG   SenderThread:85754 [sender.py:send():235] send: header
2022-02-17 18:58:34,486 INFO    WriterThread:85754 [datastore.py:open_for_write():77] open: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/run-tdyohf2i.wandb
2022-02-17 18:58:34,487 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: check_version
2022-02-17 18:58:34,488 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: check_version
2022-02-17 18:58:34,839 DEBUG   SenderThread:85754 [sender.py:send():235] send: run
2022-02-17 18:58:35,315 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: run_start
2022-02-17 18:58:35,336 DEBUG   HandlerThread:85754 [meta.py:__init__():36] meta init
2022-02-17 18:58:35,336 DEBUG   HandlerThread:85754 [meta.py:__init__():50] meta init done
2022-02-17 18:58:35,336 DEBUG   HandlerThread:85754 [meta.py:probe():210] probe
2022-02-17 18:58:35,343 DEBUG   HandlerThread:85754 [git.py:repo():33] git repository is invalid
2022-02-17 18:58:35,343 DEBUG   HandlerThread:85754 [meta.py:_save_code():88] save code
2022-02-17 18:58:35,343 WARNING HandlerThread:85754 [meta.py:_save_code():90] unable to save code -- program entry not found
2022-02-17 18:58:35,343 DEBUG   HandlerThread:85754 [meta.py:_save_pip():54] save pip
2022-02-17 18:58:35,344 DEBUG   HandlerThread:85754 [meta.py:_save_pip():68] save pip done
2022-02-17 18:58:35,344 DEBUG   HandlerThread:85754 [meta.py:probe():248] probe done
2022-02-17 18:58:35,525 INFO    SenderThread:85754 [dir_watcher.py:__init__():169] watching files in: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files
2022-02-17 18:58:35,525 INFO    SenderThread:85754 [sender.py:_start_run_threads():809] run started: tdyohf2i with start time 1645104510
2022-02-17 18:58:35,525 DEBUG   SenderThread:85754 [sender.py:send():235] send: summary
2022-02-17 18:58:35,526 INFO    SenderThread:85754 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-17 18:58:35,990 DEBUG   SenderThread:85754 [sender.py:send():235] send: files
2022-02-17 18:58:35,990 INFO    SenderThread:85754 [sender.py:_save_file():944] saving file wandb-metadata.json with policy now
2022-02-17 18:58:36,000 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:58:36,000 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 18:58:36,050 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: pause
2022-02-17 18:58:36,051 INFO    HandlerThread:85754 [handler.py:handle_request_pause():620] stopping system metrics thread
2022-02-17 18:58:36,228 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: resume
2022-02-17 18:58:36,228 INFO    HandlerThread:85754 [handler.py:handle_request_resume():611] starting system metrics thread
2022-02-17 18:58:36,245 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: pause
2022-02-17 18:58:36,245 INFO    HandlerThread:85754 [handler.py:handle_request_pause():620] stopping system metrics thread
2022-02-17 18:58:36,418 DEBUG   SenderThread:85754 [sender.py:send():235] send: stats
2022-02-17 18:58:36,418 DEBUG   SenderThread:85754 [sender.py:send():235] send: stats
2022-02-17 18:58:36,427 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: resume
2022-02-17 18:58:36,427 INFO    HandlerThread:85754 [handler.py:handle_request_resume():611] starting system metrics thread
2022-02-17 18:58:36,444 INFO    Thread-9  :85754 [dir_watcher.py:_on_file_created():217] file/dir created: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files/output.log
2022-02-17 18:58:36,444 INFO    Thread-9  :85754 [dir_watcher.py:_on_file_created():217] file/dir created: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files/wandb-summary.json
2022-02-17 18:58:37,135 INFO    Thread-11 :85754 [upload_job.py:push():137] Uploaded file /tmp/tmp61yeh54_wandb/1n09smig-wandb-metadata.json
2022-02-17 18:58:51,423 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:58:51,424 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 18:58:52,654 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: pause
2022-02-17 18:58:52,654 INFO    HandlerThread:85754 [handler.py:handle_request_pause():620] stopping system metrics thread
2022-02-17 18:58:52,705 DEBUG   SenderThread:85754 [sender.py:send():235] send: stats
2022-02-17 18:58:52,719 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: resume
2022-02-17 18:58:52,720 INFO    HandlerThread:85754 [handler.py:handle_request_resume():611] starting system metrics thread
2022-02-17 18:58:55,453 INFO    Thread-9  :85754 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files/output.log
2022-02-17 18:59:06,790 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:59:06,797 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 18:59:08,464 INFO    Thread-9  :85754 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files/output.log
2022-02-17 18:59:18,971 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: pause
2022-02-17 18:59:18,971 INFO    HandlerThread:85754 [handler.py:handle_request_pause():620] stopping system metrics thread
2022-02-17 18:59:19,046 DEBUG   SenderThread:85754 [sender.py:send():235] send: stats
2022-02-17 18:59:22,630 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:59:22,631 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 18:59:37,999 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:59:38,007 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 18:59:53,368 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 18:59:53,370 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:00:08,720 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:00:08,721 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:00:24,111 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:00:24,111 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:00:39,477 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:00:39,477 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:00:55,018 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:00:55,019 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:01:10,398 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:01:10,399 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:01:25,763 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:01:25,763 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:01:41,098 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:01:41,098 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:01:56,467 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:01:56,468 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:02:11,823 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:02:11,823 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:02:27,165 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:02:27,165 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:02:42,514 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:02:42,515 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:02:57,886 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:02:57,887 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:03:13,316 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:03:13,316 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:03:28,671 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:03:28,672 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:03:44,274 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:03:44,275 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:03:59,630 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:03:59,630 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:04:02,886 ERROR   SenderThread:85754 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f43a97b76d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/somesh/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43a97b76d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/somesh/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/somesh/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43a97b76d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-02-17 19:04:04,612 INFO    Thread-9  :85754 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files/output.log
2022-02-17 19:04:19,630 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:04:19,631 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:04:35,003 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:04:35,004 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:04:50,384 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:04:50,384 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:05:06,215 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:05:06,216 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:05:21,606 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:05:21,607 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:05:37,137 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:05:37,138 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:05:52,500 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:05:52,500 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:06:08,153 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:06:08,160 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:06:23,656 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:06:23,657 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:06:39,055 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:06:39,055 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:06:54,500 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:06:54,501 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:07:09,904 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:07:09,910 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:07:25,272 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:07:25,274 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:07:40,660 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:07:40,660 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:07:56,006 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:07:56,008 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:08:11,400 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:08:11,400 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:08:26,756 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:08:26,757 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:08:42,184 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:08:42,193 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:08:57,601 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:08:57,604 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:09:12,957 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:09:12,958 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:09:28,394 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:09:28,405 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:09:43,759 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:09:43,759 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:09:59,106 DEBUG   HandlerThread:85754 [handler.py:handle_request():131] handle_request: stop_status
2022-02-17 19:09:59,107 DEBUG   SenderThread:85754 [sender.py:send_request():249] send_request: stop_status
2022-02-17 19:10:04,205 WARNING MainThread:85754 [internal.py:is_dead():380] Internal process exiting, parent pid 85707 disappeared
2022-02-17 19:10:04,205 ERROR   MainThread:85754 [internal.py:wandb_internal():148] Internal process shutdown.
2022-02-17 19:10:04,518 INFO    SenderThread:85754 [sender.py:finish():1075] shutting down sender
2022-02-17 19:10:04,518 INFO    SenderThread:85754 [dir_watcher.py:finish():283] shutting down directory watcher
2022-02-17 19:10:04,864 INFO    SenderThread:85754 [dir_watcher.py:finish():313] scan: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/files
2022-02-17 19:10:04,864 INFO    SenderThread:85754 [file_pusher.py:finish():177] shutting down file pusher
2022-02-17 19:10:04,864 INFO    SenderThread:85754 [file_pusher.py:join():182] waiting for file pusher
2022-02-17 19:10:05,074 INFO    WriterThread:85754 [datastore.py:close():281] close: /home/somesh/Desktop/code/Python_stuff/ZEST AI data analysis exercise/wandb/run-20220217_185830-tdyohf2i/run-tdyohf2i.wandb
2022-02-17 19:10:05,120 INFO    HandlerThread:85754 [handler.py:finish():739] shutting down handler
2022-02-17 19:10:05,680 INFO    MainThread:85754 [internal.py:handle_exit():79] Internal process exited
